# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
---
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# scripts that run after cloning repository
install:
  - nuget restore

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"

